### ISSUE TITLE
申请授权成功，但发送时提示账号未登录

### ISSUE THREAD

**Issue by Snownee** [Bililive/SendDanmaku#4]
![image](https://user-images.githubusercontent.com/16059084/54924526-91dd9100-4f47-11e9-99d2-824d85324e9e.png)
![image](https://user-images.githubusercontent.com/16059084/54924544-986c0880-4f47-11e9-89cb-244765bd10ce.png)

**Comment by dawn-lc** [comment]
去登陆中心登录一下你的B站账号
![QQ截图20190325215504](https://user-images.githubusercontent.com/30336566/54925193-c6058180-4f48-11e9-87d2-f7563b7588e8.jpg)
![QQ截图20190325215450](https://user-images.githubusercontent.com/30336566/54925199-c9990880-4f48-11e9-980d-d83a35aa3817.jpg)
